### ISSUE TITLE
Facebook Integration

### ISSUE THREAD

**Issue by jeffh** [jeffh/YACS#8]
Lots of students like to share schedules via Facebook. Research needs to be done to see how this is done and the best approach.

**Comment by arpit1997** [comment]
I can suggest an approach to implement this feature. But we would require a new feature called Login with Facebook. I don't know if it is feasible or not but we can use [Facebook Graph API](https://developers.facebook.com/docs/) for this. We can implement a share on Facebook popup like thing so that users have the flexibility for choosing which people to share with. @jeffh you may follow this [link](https://developers.facebook.com/docs/sharing/reference/share-dialog) for more details. 
Hope this helps :smile: :smile:

**Comment by jeffh** [comment]
It's probably better to forward this to the new repository https://github.com/YACS-RCOS/yacs. RPI has requested yacs.me to shutdown to use that one instead: https://yacs.cs.rpi.edu/
